//! Audio — load sounds at startup, play them synchronously during the game loop.
//!
//! The basic pattern for every game:
//! 1. At startup (inside `async fn main`), load each sound with `load_sound()` or `beep()`.
//! 2. Store the returned `BlipSound` handles somewhere (usually a `Sounds` struct).
//! 3. Call `play_sfx()`, `play_music()`, or `play_ambient()` whenever you need them — these
//!    are synchronous and can be called freely inside the game loop.

use std::f32::consts::PI;
use std::sync::Mutex;

use macroquad::audio::{
    load_sound_from_bytes, play_sound, play_sound_once, stop_sound, PlaySoundParams, Sound,
};

/// An opaque handle to a decoded sound. Store these at startup; replaying them is free.
pub type BlipSound = Sound;

/// Decode a WAV byte slice into a `BlipSound`. Must be awaited at startup —
/// do not call this inside the game loop.
pub async fn load_sound(bytes: &'static [u8]) -> BlipSound {
    load_sound_from_bytes(bytes)
        .await
        .expect("blip::audio::load_sound: decode failed")
}

/// Play a sound effect once at full volume.
pub fn play_sfx(s: &BlipSound) {
    play_sound_once(s);
}

/// Play a sound effect once at a specific volume (0.0 = silent, 1.0 = full).
pub fn play_sfx_volume(s: &BlipSound, volume: f32) {
    play_sound(s, PlaySoundParams { looped: false, volume });
}

static CURRENT_MUSIC: Mutex<Option<Sound>> = Mutex::new(None);

/// Start looping background music. Replaces any currently playing music.
/// Volume is set to 0.7 — up front in the mix, not background wallpaper.
pub fn play_music(s: &BlipSound) {
    stop_music();
    play_sound(s, PlaySoundParams { looped: true, volume: 0.7 });
    if let Ok(mut guard) = CURRENT_MUSIC.lock() {
        *guard = Some(s.clone());
    }
}

pub fn stop_music() {
    if let Ok(mut guard) = CURRENT_MUSIC.lock() {
        if let Some(s) = guard.take() {
            stop_sound(&s);
        }
    }
}

static CURRENT_AMBIENT: Mutex<Option<Sound>> = Mutex::new(None);

/// Start looping ambient sound (e.g. wind, ocean). Quieter than music at volume 0.18.
pub fn play_ambient(s: &BlipSound) {
    stop_ambient();
    play_sound(s, PlaySoundParams { looped: true, volume: 0.18 });
    if let Ok(mut guard) = CURRENT_AMBIENT.lock() {
        *guard = Some(s.clone());
    }
}

pub fn stop_ambient() {
    if let Ok(mut guard) = CURRENT_AMBIENT.lock() {
        if let Some(s) = guard.take() {
            stop_sound(&s);
        }
    }
}

/// Synthesize a short punchy beep and return it as a `BlipSound` — no WAV file needed.
/// `freq` is in Hz (e.g. 440.0 for concert A), `duration_ms` is the length in milliseconds.
/// Await this at startup; the returned handle can be replayed freely with `play_sfx`.
/// The generated bytes are intentionally leaked onto the heap because macroquad requires a
/// `'static` slice, and each game creates only a handful of beeps for its entire lifetime.
///
/// The tone is a fundamental blended with a soft third harmonic and a touch of tanh
/// saturation, with a fast attack and a slight downward pitch drift — a snappier, more
/// "synth" character than a bare sine, without changing the call site's feel or cost.
pub async fn beep(freq: f32, duration_ms: f32) -> BlipSound {
    let bytes = synth_beep_wav(freq, duration_ms);
    let leaked: &'static [u8] = Box::leak(bytes.into_boxed_slice());
    load_sound(leaked).await
}

fn synth_beep_wav(freq: f32, duration_ms: f32) -> Vec<u8> {
    const SR: u32 = 44_100;
    let n = (SR as f32 * duration_ms / 1000.0) as usize;
    let attack = ((SR as usize) / 500).max(1).min(n / 4 + 1);
    let mut samples: Vec<i16> = Vec::with_capacity(n);
    for i in 0..n {
        let t = i as f32 / SR as f32;
        let env = if i < attack {
            i as f32 / attack as f32
        } else {
            let d = (i - attack) as f32 / (n - attack).max(1) as f32;
            (1.0 - d).powf(1.6)
        };
        let drift = 1.0 - 0.05 * (i as f32 / n as f32); // slight downward pitch character
        let f = freq * drift;
        let fund = (2.0 * PI * f * t).sin();
        let third = (2.0 * PI * f * 3.0 * t).sin() / 3.0;
        let shaped = (fund * 0.8 + third * 0.35).tanh();
        let s = (env * 11_500.0 * shaped) as i16;
        samples.push(s);
    }
    encode_wav(SR, &samples)
}

fn encode_wav(sample_rate: u32, samples: &[i16]) -> Vec<u8> {
    let n = samples.len();
    let data_bytes = (n * 2) as u32;
    let mut out = Vec::with_capacity(44 + n * 2);
    out.extend_from_slice(b"RIFF");
    out.extend_from_slice(&(36 + data_bytes).to_le_bytes());
    out.extend_from_slice(b"WAVE");
    out.extend_from_slice(b"fmt ");
    out.extend_from_slice(&16u32.to_le_bytes());
    out.extend_from_slice(&1u16.to_le_bytes()); // PCM
    out.extend_from_slice(&1u16.to_le_bytes()); // mono
    out.extend_from_slice(&sample_rate.to_le_bytes());
    out.extend_from_slice(&(sample_rate * 2).to_le_bytes());
    out.extend_from_slice(&2u16.to_le_bytes());
    out.extend_from_slice(&16u16.to_le_bytes());
    out.extend_from_slice(b"data");
    out.extend_from_slice(&data_bytes.to_le_bytes());
    for s in samples {
        out.extend_from_slice(&s.to_le_bytes());
    }
    out
}
