#!/usr/bin/env python3
"""Writes web/wear.css: forty years in the back room of a bar.

The cabinet is kept clean and polished, but it has been played all night, every
night: scratches from keys and rings, scuffs from shoes, palm-worn patches,
cigarette burns and the rings of damp glasses on its ledge.

    python3 tools/make_wear.py

The scratch patterns are drawn here with a fixed seed, so the file comes out
the same each time.
"""

import random
from pathlib import Path
from urllib.parse import quote

OUT = Path(__file__).resolve().parent.parent / "web" / "wear.css"


def url(svg):
    return 'url("data:image/svg+xml,' + quote(svg, safe="/:=;,'()") + '")'


def scratches(w, h, seed, count, angle, light="#e8cfa0", spread=7.0):
    """Hairline scratches mostly along `angle` (degrees), a few gouges across it."""
    import math
    rng = random.Random(seed)
    lines = []
    for i in range(count):
        wander = rng.gauss(0, spread) if rng.random() > 0.15 else rng.uniform(-90, 90)
        a = math.radians(angle + wander)
        length = rng.uniform(0.03, 0.4) * max(w, h) * (rng.random() ** 2 + 0.15)
        x, y = rng.uniform(0, w), rng.uniform(0, h)
        dx, dy = math.cos(a) * length, math.sin(a) * length
        deep = rng.random() < 0.18
        colour = "#000" if deep else light
        opacity = rng.uniform(0.25, 0.45) if deep else rng.uniform(0.07, 0.26)
        width = rng.uniform(0.7, 1.4) if deep else rng.uniform(0.35, 0.9)
        lines.append(
            f"<line x1='{x:.1f}' y1='{y:.1f}' x2='{x + dx:.1f}' y2='{y + dy:.1f}' "
            f"stroke='{colour}' stroke-opacity='{opacity:.2f}' stroke-width='{width:.2f}' stroke-linecap='round'/>")
    return url(f"<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 {w} {h}' preserveAspectRatio='none'>"
               + "".join(lines) + "</svg>")


def grain(seed, warm):
    """Fine speckle: dust and worn finish."""
    rgb = "0.62 0.46 0.30" if warm else "1 1 1"
    r, g, b = rgb.split()
    return url(
        "<svg xmlns='http://www.w3.org/2000/svg' width='180' height='180'>"
        f"<filter id='n'><feTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='2' seed='{seed}'/>"
        f"<feColorMatrix values='0 0 0 0 {r} 0 0 0 0 {g} 0 0 0 0 {b} 0 0 0 0.55 -0.255'/></filter>"
        "<rect width='180' height='180' filter='url(#n)'/></svg>")


# A burn: a charred core, a scorched ring, then the smoke that browned the finish around it.
def burn(x, y, rx, ry):
    return (f"radial-gradient(ellipse {rx}px {ry}px at {x}% {y}%, #0c0603 0 38%, #2b170a 52%, "
            f"rgba(96,52,20,.55) 70%, rgba(96,52,20,0) 100%)")


# The dried rim a wet glass leaves.
def ring(x, y, r):
    return (f"radial-gradient(circle {r}px at {x}% {y}%, rgba(214,178,120,0) {r - 5}px, "
            f"rgba(214,178,120,.17) {r - 3}px, rgba(214,178,120,.06) {r - 1.5}px, rgba(214,178,120,0) {r}px)")


def patch(x, y, rx, ry, rgba):
    return f"radial-gradient(ellipse {rx}px {ry}px at {x}% {y}%, {rgba}, rgba(0,0,0,0))"


CSS = f"""/* Generated by tools/make_wear.py: do not edit by hand.
   Forty years in the back room of a bar. Kept clean and polished, but played
   every night: scratched, scuffed, burnt and ringed where a night's play lands. */

/* The wood: hairline scratches, a smoker's brown at the top edge, fine grain. */
:root {{
  --wear-scratches-wide: {scratches(800, 100, 11, 70, 2)};
  --wear-grain: {grain(5, True)};
  --cabinet-wood:
    {grain(9, True)} 0 0 / 180px 180px,
    {scratches(800, 100, 12, 55, 3)} center / 100% 100% no-repeat,
    linear-gradient(180deg, rgba(120, 82, 36, .20), rgba(120, 82, 36, 0) 55%),
    repeating-linear-gradient(174deg, transparent 0 13px, rgba(240, 207, 164, .028) 14px, transparent 16px 28px),
    linear-gradient(110deg, rgba(255, 229, 187, .035), transparent 35% 75%, rgba(0, 0, 0, .12)),
    linear-gradient(155deg, #50372b 0%, #362720 18%, #211a1c 62%, #100e12 100%);
}}

/* The side rails: shoe scuffs at the foot, a knee-high rub, scratches running down. */
.cab-rail::before {{
  content: ''; position: absolute; inset: 0; pointer-events: none;
  background:
    {burn(62, 26, 5, 8)},
    {patch(50, 100, 70, 130, 'rgba(0, 0, 0, .5)')},
    {patch(50, 82, 50, 90, 'rgba(210, 170, 110, .09)')},
    {scratches(64, 800, 21, 60, 88, spread=5)} center / 100% 100% no-repeat,
    {grain(3, True)} 0 0 / 180px 180px;
}}

/* The ledge in front of the controls: rings, burns and the grime of a thousand elbows. Only upright:
   sideways, the deck is a transparent layer of controls over the picture. */
:root[data-layout="upright"] .snes-shell::before,
:root[data-layout="upright"] .kiosk-bar > .deck-panel::before {{
  content: ''; position: absolute; inset: 0; z-index: 0; pointer-events: none; border-radius: inherit;
  background:
    {burn(38, 9, 13, 7)},
    {burn(42, 13, 8, 5)},
    {burn(83, 10, 11, 6)},
    {ring(67, 55, 22)},
    {ring(70, 63, 21)},
    {ring(22, 22, 20)},
    {patch(50, 118, 360, 70, 'rgba(210, 170, 110, .13)')},
    {patch(18, 60, 70, 50, 'rgba(210, 170, 110, .08)')},
    {patch(0, 50, 60, 130, 'rgba(0, 0, 0, .35)')},
    {patch(100, 50, 60, 130, 'rgba(0, 0, 0, .35)')},
    {scratches(760, 112, 31, 90, 4)} center / 100% 100% no-repeat,
    {grain(7, True)} 0 0 / 180px 180px;
}}

/* The cross: its middle polished bright by thumbs, the rim chipped. */
.snes-dpad::after {{
  content: ''; position: absolute; inset: 0; z-index: 2; pointer-events: none;
  background:
    radial-gradient(circle 15px at 50% 50%, rgba(255, 255, 255, .17), rgba(255, 255, 255, 0) 100%),
    radial-gradient(circle 3px at 50% 50%, rgba(255, 255, 255, .12), rgba(255, 255, 255, 0)),
    radial-gradient(ellipse 6px 3px at 12% 46%, rgba(255, 255, 255, .13), rgba(255, 255, 255, 0)),
    radial-gradient(ellipse 5px 3px at 88% 55%, rgba(255, 255, 255, .11), rgba(255, 255, 255, 0));
}}

/* The red buttons: gloss worn to a dull, scuffed middle, chipped at the edge, still clean. */
.snes-btn::after {{
  content: ''; position: absolute; inset: 0; z-index: 3; pointer-events: none; border-radius: 50%;
  background:
    radial-gradient(circle 4px at 20% 30%, rgba(255, 230, 215, .35), rgba(255, 230, 215, 0)),
    radial-gradient(circle 3px at 80% 70%, rgba(40, 0, 0, .35), rgba(40, 0, 0, 0)),
    radial-gradient(ellipse 60% 55% at 50% 52%, rgba(255, 190, 170, .20), rgba(255, 190, 170, 0)),
    {scratches(60, 50, 41, 22, -30, light='#ffd8cc', spread=25)} center / 100% 100% no-repeat;
}}

/* The coin plate: brushed metal gone dull in its middle, scratched by keys and coins. */
.coin-plate::after {{
  content: ''; position: absolute; inset: 0; z-index: 3; pointer-events: none; border-radius: inherit;
  background:
    {patch(50, 78, 38, 20, 'rgba(0, 0, 0, .22)')},
    {patch(15, 10, 30, 30, 'rgba(70, 50, 20, .20)')},
    {patch(88, 92, 28, 22, 'rgba(70, 50, 20, .20)')},
    {scratches(91, 104, 51, 55, 20, light='#ffffff', spread=30)} center / 100% 100% no-repeat,
    {grain(2, False)} 0 0 / 180px 180px;
}}

/* The glass over the cards was replaced five years ago: clean, with only a little dust in one corner. */
.cabinet-glass::after {{
  content: ''; position: absolute; inset: 0; pointer-events: none; border-radius: inherit;
  background: {patch(90, 95, 60, 36, 'rgba(255, 255, 255, .03)')};
}}

/* The printed cards: yellowed at the edges, and each one handled in its own way. The overlay
   hangs from .card-desc but covers the whole sheet, which is its positioned ancestor. */
.card-desc::after {{
  content: ''; position: absolute; inset: 0; pointer-events: none; border-radius: inherit;
  background:
    linear-gradient(90deg, rgba(120, 84, 40, .22), rgba(120, 84, 40, 0) 9%, rgba(120, 84, 40, 0) 91%, rgba(120, 84, 40, .22)),
    linear-gradient(180deg, rgba(120, 84, 40, .14), rgba(120, 84, 40, 0) 14%, rgba(120, 84, 40, 0) 86%, rgba(120, 84, 40, .18));
}}
.card:nth-child(3n + 1) .card-desc::after {{
  background:
    radial-gradient(circle 27px at 84% 74%, rgba(130, 84, 40, 0) 22px, rgba(130, 84, 40, .26) 24px, rgba(130, 84, 40, .09) 26px, rgba(130, 84, 40, 0) 27px),
    radial-gradient(circle 22px at 84% 74%, rgba(130, 84, 40, .07), rgba(130, 84, 40, 0)),
    linear-gradient(90deg, rgba(120, 84, 40, .22), rgba(120, 84, 40, 0) 9%, rgba(120, 84, 40, 0) 91%, rgba(120, 84, 40, .22));
}}
.card:nth-child(3n + 2) .card-desc::after {{
  background:
    radial-gradient(ellipse 20px 28px at 16% 76%, rgba(90, 60, 30, .17), rgba(90, 60, 30, 0)),
    radial-gradient(ellipse 14px 20px at 24% 86%, rgba(90, 60, 30, .12), rgba(90, 60, 30, 0)),
    linear-gradient(315deg, rgba(0, 0, 0, 0) 93.5%, rgba(95, 72, 42, .55) 94.5%, rgba(246, 236, 210, .9) 96%),
    linear-gradient(90deg, rgba(120, 84, 40, .22), rgba(120, 84, 40, 0) 9%, rgba(120, 84, 40, 0) 91%, rgba(120, 84, 40, .22));
}}
.card:nth-child(3n) .card-desc::after {{
  background:
    radial-gradient(ellipse 46px 9px at 58% 91%, rgba(50, 50, 50, .22), rgba(50, 50, 50, 0)),
    radial-gradient(circle 1.5px at 30% 20%, rgba(60, 40, 20, .5), rgba(60, 40, 20, 0)),
    radial-gradient(circle 1px at 71% 34%, rgba(60, 40, 20, .45), rgba(60, 40, 20, 0)),
    radial-gradient(circle 1.2px at 52% 62%, rgba(60, 40, 20, .4), rgba(60, 40, 20, 0)),
    linear-gradient(90deg, rgba(120, 84, 40, .22), rgba(120, 84, 40, 0) 9%, rgba(120, 84, 40, 0) 91%, rgba(120, 84, 40, .22));
}}
"""

OUT.write_text(CSS)
print(f"wrote {OUT} ({len(CSS):,} bytes)")
